uvmf:
  environments:
    decode:
      agents:
      - initiator_responder: INITIATOR
        name: din_agent
        type: decode_in
      - initiator_responder: RESPONDER
        name: dout_agent
        type: decode_out
      analysis_components:
      - name: d_predictor
        parameters: []
        type: decode_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: d_scoreboard
        sb_type: uvmf_in_order_race_scoreboard
        trans_type: decode_out_transaction
      subenvs: []
      tlm_connections:
      - driver: din_agent.monitored_ap
        receiver: d_predictor.d_analysis_export
        validate: 'True'
      - driver: dout_agent.monitored_ap
        receiver: d_scoreboard.actual_analysis_export
        validate: 'True'
      - driver: d_predictor.d_analysis_port
        receiver: d_scoreboard.expected_analysis_export
        validate: 'True'
