uvmf:
  environments:
    execute:
      agents:
      - initiator_responder: INITIATOR
        name: exin_agent
        type: execute_in
      - initiator_responder: RESPONDER
        name: exout_agent
        type: execute_out
      analysis_components:
      - name: ex_predictor
        parameters: []
        type: execute_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: ex_scoreboard
        sb_type: uvmf_in_order_race_scoreboard
        trans_type: execute_out_transaction
      subenvs: []
      tlm_connections:
      - driver: exin_agent.monitored_ap
        receiver: ex_predictor.analysis_export
        validate: 'True'
      - driver: exout_agent.monitored_ap
        receiver: ex_scoreboard.actual_analysis_export
        validate: 'True'
      - driver: ex_predictor.analysis_port
        receiver: ex_scoreboard.expected_analysis_export
        validate: 'True'
