uvmf:
  environments:
    fetch:
      agents:
      - initiator_responder: INITIATOR
        name: In_Agent
        type: fetch_in
      - initiator_responder: RESPONDER
        name: Out_Agent
        type: fetch_out
      analysis_components:
      - name: predictor
        parameters: []
        type: fetch_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      - name: fetch_in_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: scbd0
        sb_type: uvmf_in_order_scoreboard
        trans_type: fetch_out_transaction
      subenvs: []
      tlm_connections:
      - driver: In_Agent.monitored_ap
        receiver: predictor.analysis_export
        validate: 'True'
      - driver: Out_Agent.monitored_ap
        receiver: scbd0.actual_analysis_export
        validate: 'True'
      - driver: predictor.analysis_port
        receiver: scbd0.expected_analysis_export
        validate: 'True'
